/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizMS;

import static QuizMS.QusAppt1.count2;
import static QuizMS.QusAppt1.notatp2;
import static QuizMS.QusAppt1.score2;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author devan
 */
public class QusApt2 extends javax.swing.JFrame {

    /**
     * Creates new form QusApt2
     */
    Container c;
    public QusApt2() {
        initComponents();
        c=getContentPane();
        c.setBackground(Color.white);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        q5opt1 = new javax.swing.JRadioButton();
        q5opt2 = new javax.swing.JRadioButton();
        q5opt3 = new javax.swing.JRadioButton();
        q5opt4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        q6opt1 = new javax.swing.JRadioButton();
        q6opt2 = new javax.swing.JRadioButton();
        q6opt3 = new javax.swing.JRadioButton();
        q6opt4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        q7opt1 = new javax.swing.JRadioButton();
        q7opt2 = new javax.swing.JRadioButton();
        q7opt3 = new javax.swing.JRadioButton();
        q7opt4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        q8opt1 = new javax.swing.JRadioButton();
        q8opt2 = new javax.swing.JRadioButton();
        q8opt3 = new javax.swing.JRadioButton();
        q8opt4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        q5 = new javax.swing.JLabel();
        q6 = new javax.swing.JLabel();
        q7 = new javax.swing.JLabel();
        q8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Look at this series: 53, 53, 40, 40, 27, 27, ... What number should come next?");

        buttonGroup1.add(q5opt1);
        q5opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5opt1.setText("12");

        buttonGroup1.add(q5opt2);
        q5opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5opt2.setText("14");

        buttonGroup1.add(q5opt3);
        q5opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5opt3.setText("27");

        buttonGroup1.add(q5opt4);
        q5opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5opt4.setText("53");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Look at this series: 58, 52, 46, 40, 34, ... What number should come next?");

        buttonGroup2.add(q6opt1);
        q6opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6opt1.setText("26");

        buttonGroup2.add(q6opt2);
        q6opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6opt2.setText("28");

        buttonGroup2.add(q6opt3);
        q6opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6opt3.setText("30");
        q6opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6opt3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(q6opt4);
        q6opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6opt4.setText("32");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Look at this series: 14, 28, 20, 40, 32, 64, ... What number should come next?");

        buttonGroup3.add(q7opt1);
        q7opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7opt1.setText("52");

        buttonGroup3.add(q7opt2);
        q7opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7opt2.setText("56");

        buttonGroup3.add(q7opt3);
        q7opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7opt3.setText("96");

        buttonGroup3.add(q7opt4);
        q7opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7opt4.setText("128");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Look at this series: 80, 10, 70, 15, 60, ... What number should come next?");

        buttonGroup4.add(q8opt1);
        q8opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8opt1.setText("20");

        buttonGroup4.add(q8opt2);
        q8opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8opt2.setText("25");

        buttonGroup4.add(q8opt3);
        q8opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8opt3.setText("30");

        buttonGroup4.add(q8opt4);
        q8opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8opt4.setText("50");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        q5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5.setText("5");

        q6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6.setText("6");

        q7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7.setText("7");

        q8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8.setText("8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q5)
                    .addComponent(q7)
                    .addComponent(q8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q5opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q5opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q5opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q5opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q6opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q6opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q6opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q6opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q7opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q7opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q7opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q7opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q8opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q8opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q8opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q8opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(178, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(q5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5opt1)
                    .addComponent(q5opt2)
                    .addComponent(q5opt3)
                    .addComponent(q5opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(q6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6opt1)
                    .addComponent(q6opt2)
                    .addComponent(q6opt3)
                    .addComponent(q6opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(q7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7opt1)
                    .addComponent(q7opt2)
                    .addComponent(q7opt3)
                    .addComponent(q7opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(q8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8opt1)
                    .addComponent(q8opt2)
                    .addComponent(q8opt3)
                    .addComponent(q8opt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int qid5=Integer.parseInt(q5.getText());
        int qid6=Integer.parseInt(q6.getText());
        int qid7=Integer.parseInt(q7.getText());
        int qid8=Integer.parseInt(q8.getText());
        
        String res5="";
        String res6="";
        String res7="";
        String res8="";
       
            
                if(q5opt1.isSelected()==true)
                { 
                    res5=q5opt1.getText();
                }
                else if(q5opt2.isSelected()==true)
                { 
                    res5=q5opt2.getText(); 
                }
                else if(q5opt3.isSelected()==true)
                { 
                    res5=q5opt3.getText();  
                }
                else if(q5opt4.isSelected()==true)
                { 
                    res5=q5opt4.getText();  
                }
                else if(q5opt1.isSelected()==false&&q5opt2.isSelected()==false&&q5opt3.isSelected()==false&&q5opt4.isSelected()==false)
                {
                    notatp2++;
                }
                
                if(q6opt1.isSelected()==true)
                { 
                    res6=q6opt1.getText();
                }
                else if(q6opt2.isSelected()==true)
                { 
                    res6=q6opt2.getText(); 
                }
                else if(q6opt3.isSelected()==true)
                { 
                    res6=q6opt3.getText();  
                }
                else if(q6opt4.isSelected()==true)
                { 
                    res6=q6opt4.getText();  
                }
                else if(q6opt1.isSelected()==false&&q6opt2.isSelected()==false&&q6opt3.isSelected()==false&&q6opt4.isSelected()==false)
                {
                    notatp2++;
                }
                
                if(q7opt1.isSelected()==true)
                { 
                    res7=q7opt1.getText();
                }
                else if(q7opt2.isSelected()==true)
                { 
                    res7=q7opt2.getText(); 
                }
                else if(q7opt3.isSelected()==true)
                { 
                    res7=q7opt3.getText();  
                }
                else if(q7opt4.isSelected()==true)
                { 
                    res7=q7opt4.getText();  
                }
                else if(q7opt1.isSelected()==false&&q7opt2.isSelected()==false&&q7opt3.isSelected()==false&&q7opt4.isSelected()==false)
                {
                    notatp2++;
                }
                
                if(q8opt1.isSelected()==true)
                { 
                    res8=q8opt1.getText();
                }
                else if(q8opt2.isSelected()==true)
                { 
                    res8=q8opt2.getText(); 
                }
                else if(q8opt3.isSelected()==true)
                { 
                    res8=q8opt3.getText();  
                }
                else if(q8opt4.isSelected()==true)
                { 
                    res8=q8opt4.getText();  
                }
                else if(q8opt1.isSelected()==false||q8opt2.isSelected()==false||q8opt3.isSelected()==false||q8opt4.isSelected()==false)
                {
                    notatp2++;
                }
                else{
                    System.out.println("Wrong...");
                }      
                int count3 = 0;
                try{
                    Connection con=ConnectionCode.getcon();
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery("Select qus_id,answer_key from questionsapt");
                    while(rs.next()){
                        if (count3 >= 4 && count3 < 8) {
                        int qus_id=rs.getInt("qus_id");
                        String ans1=rs.getString("answer_key");
                        
                        if(qid5==qus_id && res5.equals(ans1)){
                            score2++;
                        }
                        else if(qid6==qus_id && res6.equals(ans1)){
                            score2++;
                        }
                        else if(qid7==qus_id && res7.equals(ans1)){
                            score2++;
                        }
                        else if(qid8==qus_id && res8.equals(ans1)){
                            score2++;
                        }
                        else{
                            count2++;
                        }
                        //System.out.println("ans is "+ans1);
                        //System.out.println("count is "+count);
                        }
                        count3++;
                        
                    }
                    
                }catch(Exception e){
                    System.out.println(" "+e);
                }
                System.out.println("attempted qus are "+notatp2);
                /*System.out.println("ans is "+res5);
                System.out.println("ans is "+res6);
                System.out.println("ans is "+res7);
                System.out.println("ans is "+res8);
                System.out.println("score is "+score2);
                System.out.println("count is "+count2);
                  */      
        //this.dispose();
        this.toBack();
        QusApt3 qa3=new QusApt3();
        qa3.setVisible(true);
        qa3.toFront();
        qa3.setState(javax.swing.JFrame.NORMAL);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        new QusAppt1().toFront();
        new QusAppt1().setState(javax.swing.JFrame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void q6opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6opt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6opt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QusApt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QusApt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QusApt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QusApt2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new QusApt2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel q5;
    private javax.swing.JRadioButton q5opt1;
    private javax.swing.JRadioButton q5opt2;
    private javax.swing.JRadioButton q5opt3;
    private javax.swing.JRadioButton q5opt4;
    private javax.swing.JLabel q6;
    private javax.swing.JRadioButton q6opt1;
    private javax.swing.JRadioButton q6opt2;
    private javax.swing.JRadioButton q6opt3;
    private javax.swing.JRadioButton q6opt4;
    private javax.swing.JLabel q7;
    private javax.swing.JRadioButton q7opt1;
    private javax.swing.JRadioButton q7opt2;
    private javax.swing.JRadioButton q7opt3;
    private javax.swing.JRadioButton q7opt4;
    private javax.swing.JLabel q8;
    private javax.swing.JRadioButton q8opt1;
    private javax.swing.JRadioButton q8opt2;
    private javax.swing.JRadioButton q8opt3;
    private javax.swing.JRadioButton q8opt4;
    // End of variables declaration//GEN-END:variables
}
