/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizMS;

import static QuizMS.QusJava1.notatp;
import static QuizMS.QusJava1.count;
import static QuizMS.QusJava1.score;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author devan
 */
public class QusJava2 extends javax.swing.JFrame {

    /**
     * Creates new form QusJava2
     */
    Container c;
    public QusJava2() {
        initComponents();
        c=getContentPane();
        c.setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        q5opt1 = new javax.swing.JRadioButton();
        q5opt2 = new javax.swing.JRadioButton();
        q5opt3 = new javax.swing.JRadioButton();
        q5opt4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        q6opt1 = new javax.swing.JRadioButton();
        q6opt2 = new javax.swing.JRadioButton();
        q6opt3 = new javax.swing.JRadioButton();
        q6opt4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        q7opt1 = new javax.swing.JRadioButton();
        q7opt2 = new javax.swing.JRadioButton();
        q7opt3 = new javax.swing.JRadioButton();
        q7opt4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        q8opt1 = new javax.swing.JRadioButton();
        q8opt2 = new javax.swing.JRadioButton();
        q8opt3 = new javax.swing.JRadioButton();
        q8opt4 = new javax.swing.JRadioButton();
        BackButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        q5 = new javax.swing.JLabel();
        q6 = new javax.swing.JLabel();
        q7 = new javax.swing.JLabel();
        q8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Which of the following is not an access modifier in Java?");

        buttonGroup1.add(q5opt1);
        q5opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5opt1.setText(" private");

        buttonGroup1.add(q5opt2);
        q5opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5opt2.setText("protected");

        buttonGroup1.add(q5opt3);
        q5opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5opt3.setText("public");

        buttonGroup1.add(q5opt4);
        q5opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5opt4.setText("restricted");
        q5opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5opt4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("String str1 = \"Hello\";");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText(" String str2 = \"Hello\";");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText(" System.out.println(str1 == str2);");

        buttonGroup2.add(q6opt1);
        q6opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6opt1.setText("true");

        buttonGroup2.add(q6opt2);
        q6opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6opt2.setText("false");

        buttonGroup2.add(q6opt3);
        q6opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6opt3.setText("Compilation error ");

        buttonGroup2.add(q6opt4);
        q6opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6opt4.setText("Runtime error");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Which of the following methods is used to start a thread in Java?");

        buttonGroup3.add(q7opt1);
        q7opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7opt1.setText("run()");

        buttonGroup3.add(q7opt2);
        q7opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7opt2.setText("start()");

        buttonGroup3.add(q7opt3);
        q7opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7opt3.setText("begin()");

        buttonGroup3.add(q7opt4);
        q7opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7opt4.setText("execute()");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Which method is used to compare two strings in Java?");

        buttonGroup4.add(q8opt1);
        q8opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8opt1.setText("equals()");

        buttonGroup4.add(q8opt2);
        q8opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8opt2.setText("compare()");

        buttonGroup4.add(q8opt3);
        q8opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8opt3.setText("equalsIgnoreCase()");

        buttonGroup4.add(q8opt4);
        q8opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8opt4.setText("compareTo()");
        q8opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8opt4ActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(255, 0, 0));
        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        q5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q5.setText("5");

        q6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q6.setText("6");

        q7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q7.setText("7");

        q8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q8.setText("8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q5)
                            .addComponent(q6)
                            .addComponent(q7)
                            .addComponent(q8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q6opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q6opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q6opt3)
                                        .addGap(18, 18, 18)
                                        .addComponent(q6opt4))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q5opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q5opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(q5opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(q5opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(q7opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(q7opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(q7opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(q7opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(q8opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(q8opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(q8opt3)
                                                .addGap(18, 18, 18)
                                                .addComponent(q8opt4)))))
                                .addGap(0, 40, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(q5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5opt2)
                            .addComponent(q5opt3)
                            .addComponent(q5opt4)
                            .addComponent(q5opt1))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(q6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6opt1)
                    .addComponent(q6opt2)
                    .addComponent(q6opt3)
                    .addComponent(q6opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(q7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7opt1)
                    .addComponent(q7opt2)
                    .addComponent(q7opt3)
                    .addComponent(q7opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(q8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8opt1)
                    .addComponent(q8opt2)
                    .addComponent(q8opt3)
                    .addComponent(q8opt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(BackButton))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q8opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8opt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8opt4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
        int qid5=Integer.parseInt(q5.getText());
        int qid6=Integer.parseInt(q6.getText());
        int qid7=Integer.parseInt(q7.getText());
        int qid8=Integer.parseInt(q8.getText());
        
        String res5="";
        String res6="";
        String res7="";
        String res8="";
       
            
                if(q5opt1.isSelected()==true)
                { 
                    res5=q5opt1.getText();
                }
                else if(q5opt2.isSelected()==true)
                { 
                    res5=q5opt2.getText(); 
                }
                else if(q5opt3.isSelected()==true)
                { 
                    res5=q5opt3.getText();  
                }
                else if(q5opt4.isSelected()==true)
                { 
                    res5=q5opt4.getText();  
                }
                else if(q5opt1.isSelected()==false&&q5opt2.isSelected()==false&&q5opt3.isSelected()==false&&q5opt4.isSelected()==false)
                {
                    notatp++;
                }
                
                if(q6opt1.isSelected()==true)
                { 
                    res6=q6opt1.getText();
                }
                else if(q6opt2.isSelected()==true)
                { 
                    res6=q6opt2.getText(); 
                }
                else if(q6opt3.isSelected()==true)
                { 
                    res6=q6opt3.getText();  
                }
                else if(q6opt4.isSelected()==true)
                { 
                    res6=q6opt4.getText();  
                }
                else if(q6opt1.isSelected()==false&&q6opt2.isSelected()==false&&q6opt3.isSelected()==false&&q6opt4.isSelected()==false)
                {
                    notatp++;
                }
                
                if(q7opt1.isSelected()==true)
                { 
                    res7=q7opt1.getText();
                }
                else if(q7opt2.isSelected()==true)
                { 
                    res7=q7opt2.getText(); 
                }
                else if(q7opt3.isSelected()==true)
                { 
                    res7=q7opt3.getText();  
                }
                else if(q7opt4.isSelected()==true)
                { 
                    res7=q7opt4.getText();  
                }
                else if(q7opt1.isSelected()==false&&q7opt2.isSelected()==false&&q7opt3.isSelected()==false&&q7opt4.isSelected()==false)
                {
                    notatp++;
                }
                
                if(q8opt1.isSelected()==true)
                { 
                    res8=q8opt1.getText();
                }
                else if(q8opt2.isSelected()==true)
                { 
                    res8=q8opt2.getText(); 
                }
                else if(q8opt3.isSelected()==true)
                { 
                    res8=q8opt3.getText();  
                }
                else if(q8opt4.isSelected()==true)
                { 
                    res8=q8opt4.getText();  
                }
                else if(q8opt1.isSelected()==false||q8opt2.isSelected()==false||q8opt3.isSelected()==false||q8opt4.isSelected()==false)
                {
                    notatp++;
                }
                else{
                    System.out.println("Wrong...");
                }      
                int count2 = 0;
                try{
                    Connection con=ConnectionCode.getcon();
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery("Select qus_id,answer_key from questionsjava");
                    while(rs.next()){
                        if (count2 >= 4 && count2 < 8) {
                        int qus_id=rs.getInt("qus_id");
                        String ans1=rs.getString("answer_key");
                        
                        if(qid5==qus_id && res5.equals(ans1)){
                            score++;
                        }
                        else if(qid6==qus_id && res6.equals(ans1)){
                            score++;
                        }
                        else if(qid7==qus_id && res7.equals(ans1)){
                            score++;
                        }
                        else if(qid8==qus_id && res8.equals(ans1)){
                            score++;
                        }
                        else{
                            count++;
                        }
                        //System.out.println("score is "+score);
                        //System.out.println("count is "+count);
                        }
                        count2++;
                        
                    }
                    
                }catch(Exception e){
                    System.out.println(" "+e);
                }
        //this.dispose();
        this.toBack();
        QusJava3 qj3=new QusJava3();
        qj3.setVisible(true);
        qj3.toFront();
        qj3.setState(javax.swing.JFrame.NORMAL);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
        this.toBack();
        new QusJava1().toFront();
        new QusJava1().setState(javax.swing.JFrame.NORMAL);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void q5opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5opt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5opt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QusJava2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QusJava2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QusJava2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QusJava2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new QusJava2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel q5;
    private javax.swing.JRadioButton q5opt1;
    private javax.swing.JRadioButton q5opt2;
    private javax.swing.JRadioButton q5opt3;
    private javax.swing.JRadioButton q5opt4;
    private javax.swing.JLabel q6;
    private javax.swing.JRadioButton q6opt1;
    private javax.swing.JRadioButton q6opt2;
    private javax.swing.JRadioButton q6opt3;
    private javax.swing.JRadioButton q6opt4;
    private javax.swing.JLabel q7;
    private javax.swing.JRadioButton q7opt1;
    private javax.swing.JRadioButton q7opt2;
    private javax.swing.JRadioButton q7opt3;
    private javax.swing.JRadioButton q7opt4;
    private javax.swing.JLabel q8;
    private javax.swing.JRadioButton q8opt1;
    private javax.swing.JRadioButton q8opt2;
    private javax.swing.JRadioButton q8opt3;
    private javax.swing.JRadioButton q8opt4;
    // End of variables declaration//GEN-END:variables
}
