/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizMS;

import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonModel;

/**
 *
 * @author devan
 */
            
public class QusJava1 extends javax.swing.JFrame {

    /**
     * Creates new form QusJava1
     */
    public static int count=0;
    public static int score=0;
    public static int notatp=0;
   
    Container c;
    public QusJava1() {
        initComponents();
        c=getContentPane();
        c.setBackground(Color.white);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        q1opt1 = new javax.swing.JRadioButton();
        q1opt2 = new javax.swing.JRadioButton();
        q1opt3 = new javax.swing.JRadioButton();
        q1opt4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        q2opt1 = new javax.swing.JRadioButton();
        q2opt2 = new javax.swing.JRadioButton();
        q2opt3 = new javax.swing.JRadioButton();
        q2opt4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        q3opt1 = new javax.swing.JRadioButton();
        q3opt2 = new javax.swing.JRadioButton();
        q3opt3 = new javax.swing.JRadioButton();
        q3opt4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        q4opt1 = new javax.swing.JRadioButton();
        q4opt2 = new javax.swing.JRadioButton();
        q4opt3 = new javax.swing.JRadioButton();
        q4opt4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nm = new javax.swing.JTextField();
        q1 = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        q3 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        showtopic = new javax.swing.JLabel();
        showname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("JAVA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("What is the default value of a boolean variable in Java?");

        buttonGroup1.add(q1opt1);
        q1opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q1opt1.setText("true");

        buttonGroup1.add(q1opt2);
        q1opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q1opt2.setText("false");

        buttonGroup1.add(q1opt3);
        q1opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q1opt3.setText(" null");

        buttonGroup1.add(q1opt4);
        q1opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q1opt4.setText(" 0");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Which of these is not a valid Java data type?");

        buttonGroup2.add(q2opt1);
        q2opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q2opt1.setText("int");

        buttonGroup2.add(q2opt2);
        q2opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q2opt2.setText("float");

        buttonGroup2.add(q2opt3);
        q2opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q2opt3.setText("real");

        buttonGroup2.add(q2opt4);
        q2opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q2opt4.setText("boolean");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("int x = 5; int y = 2; System.out.println(x / y);");

        buttonGroup3.add(q3opt1);
        q3opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q3opt1.setText("2");

        buttonGroup3.add(q3opt2);
        q3opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q3opt2.setText("2.5");

        buttonGroup3.add(q3opt3);
        q3opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q3opt3.setText(" 3");

        buttonGroup3.add(q3opt4);
        q3opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q3opt4.setText(" Compilation error");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Which method in the String class is used to get the length of a string in Java?");

        buttonGroup4.add(q4opt1);
        q4opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q4opt1.setText("size()");

        buttonGroup4.add(q4opt2);
        q4opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q4opt2.setText("length()");

        buttonGroup4.add(q4opt3);
        q4opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q4opt3.setText("getSize()");

        buttonGroup4.add(q4opt4);
        q4opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q4opt4.setText(" getLength()");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NEXT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCEL");

        q1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q1.setText("1");

        q2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q2.setText("2");

        q3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q3.setText("3");

        q4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q4.setText("4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(q3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q4opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q4opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q4opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q4opt4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q3opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q3opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q3opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q3opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q2opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q2opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q2opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q2opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q1opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q1opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q1opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q1opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showtopic, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(showname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(showname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showtopic, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(q1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1opt1)
                    .addComponent(q1opt2)
                    .addComponent(q1opt3)
                    .addComponent(q1opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(q2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2opt1)
                    .addComponent(q2opt2)
                    .addComponent(q2opt3)
                    .addComponent(q2opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(q3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3opt1)
                    .addComponent(q3opt2)
                    .addComponent(q3opt3)
                    .addComponent(q3opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(q4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4opt1)
                    .addComponent(q4opt2)
                    .addComponent(q4opt3)
                    .addComponent(q4opt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        score=0;
        count=0;
        notatp=0;
        
        int qid1=Integer.parseInt(q1.getText());
        int qid2=Integer.parseInt(q2.getText());
        int qid3=Integer.parseInt(q3.getText());
        int qid4=Integer.parseInt(q4.getText());
        
        String res1="";
        String res2="";
        String res3="";
        String res4="";
       
            
                if(q1opt1.isSelected()==true)
                { 
                    res1=q1opt1.getText();
                }
                else if(q1opt2.isSelected()==true)
                { 
                    res1=q1opt2.getText(); 
                }
                else if(q1opt3.isSelected()==true)
                { 
                    res1=q1opt3.getText();  
                }
                else if(q1opt4.isSelected()==true)
                { 
                    res1=q1opt4.getText();  
                }
                else if(q1opt1.isSelected()==false&&q1opt2.isSelected()==false&&q1opt3.isSelected()==false&&q1opt4.isSelected()==false)
                {
                    notatp++;
                }
                
                if(q2opt1.isSelected()==true)
                { 
                    res2=q2opt1.getText();
                }
                else if(q2opt2.isSelected()==true)
                { 
                    res2=q2opt2.getText(); 
                }
                else if(q2opt3.isSelected()==true)
                { 
                    res2=q2opt3.getText();  
                }
                else if(q2opt4.isSelected()==true)
                { 
                    res2=q2opt4.getText();  
                }
                else if(q2opt1.isSelected()==false&&q2opt2.isSelected()==false&&q2opt3.isSelected()==false&&q2opt4.isSelected()==false)
                {
                    notatp++;
                }
                
                if(q3opt1.isSelected()==true)
                { 
                    res3=q3opt1.getText();
                }
                else if(q3opt2.isSelected()==true)
                { 
                    res3=q3opt2.getText(); 
                }
                else if(q3opt3.isSelected()==true)
                { 
                    res3=q3opt3.getText();  
                }
                else if(q3opt4.isSelected()==true)
                { 
                    res3=q3opt4.getText();  
                }
                else if(q3opt1.isSelected()==false&&q3opt2.isSelected()==false&&q3opt3.isSelected()==false&&q3opt4.isSelected()==false)
                {
                    notatp++;
                }
                
                if(q4opt1.isSelected()==true)
                { 
                    res4=q4opt1.getText();
                }
                else if(q4opt2.isSelected()==true)
                { 
                    res4=q4opt2.getText(); 
                }
                else if(q4opt3.isSelected()==true)
                { 
                    res4=q4opt3.getText();  
                }
                else if(q4opt4.isSelected()==true)
                { 
                    res4=q4opt4.getText();  
                }
                else if(q4opt1.isSelected()==false&&q4opt2.isSelected()==false&&q4opt3.isSelected()==false&&q4opt4.isSelected()==false)
                {
                    notatp++;
                }
                else{
                    System.out.println("Wrong...");
                }      
                int count2 = 0;
                try{
                    Connection con=ConnectionCode.getcon();
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery("Select qus_id,answer_key from questionsjava");
                    while(rs.next() && count2 < 4){
                        int qus_id=rs.getInt("qus_id");
                        String ans1=rs.getString("answer_key");
                        count2++;
                        //System.out.println(qus_id);
                        //System.out.println(ans1);
                        
                        if(qid1==qus_id && res1.equals(ans1)){
                            score++;
                        }
                        else if(qid2==qus_id && res2.equals(ans1)){
                            score++;
                        }
                        else if(qid3==qus_id && res3.equals(ans1)){
                            score++;
                        }
                        else if(qid4==qus_id && res4.equals(ans1)){
                            score++;
                        }
                        else{
                            count++;
                        }
                        //System.out.println("score is "+score);
                        //System.out.println("count is "+count);                    
                        
                    }
                    
                }catch(Exception e){
                    System.out.println(" "+e);
                }
                
        
        this.toBack();
        QusJava2 qj2=new QusJava2();
        qj2.setVisible(true);
        qj2.toFront();
        qj2.setState(javax.swing.JFrame.NORMAL);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        // Check answers
            
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QusJava1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QusJava1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QusJava1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QusJava1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new QusJava1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nm;
    private javax.swing.JLabel q1;
    private javax.swing.JRadioButton q1opt1;
    private javax.swing.JRadioButton q1opt2;
    private javax.swing.JRadioButton q1opt3;
    private javax.swing.JRadioButton q1opt4;
    private javax.swing.JLabel q2;
    private javax.swing.JRadioButton q2opt1;
    private javax.swing.JRadioButton q2opt2;
    private javax.swing.JRadioButton q2opt3;
    private javax.swing.JRadioButton q2opt4;
    private javax.swing.JLabel q3;
    private javax.swing.JRadioButton q3opt1;
    private javax.swing.JRadioButton q3opt2;
    private javax.swing.JRadioButton q3opt3;
    private javax.swing.JRadioButton q3opt4;
    private javax.swing.JLabel q4;
    private javax.swing.JRadioButton q4opt1;
    private javax.swing.JRadioButton q4opt2;
    private javax.swing.JRadioButton q4opt3;
    private javax.swing.JRadioButton q4opt4;
    private javax.swing.JLabel showname;
    private javax.swing.JLabel showtopic;
    // End of variables declaration//GEN-END:variables
}
