/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizMS;

import static QuizMS.LogInForm.usname;
import static QuizMS.QusJava1.count;
import static QuizMS.QusJava1.notatp;
import static QuizMS.QusJava1.score;
import static QuizMS.StartForm.topic5;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author devan
 */
public class QusJava3 extends javax.swing.JFrame {

    /**
     * Creates new form QusJava3
     */
    Container c;
    public QusJava3() {
        initComponents();
        c=getContentPane();
        c.setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        q9opt1 = new javax.swing.JRadioButton();
        q9opt2 = new javax.swing.JRadioButton();
        q9opt3 = new javax.swing.JRadioButton();
        q9opt4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        q10opt1 = new javax.swing.JRadioButton();
        q10opt2 = new javax.swing.JRadioButton();
        q10opt3 = new javax.swing.JRadioButton();
        q10opt4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        q9 = new javax.swing.JLabel();
        q10 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Which of the following keywords is used for exception handling in Java?");

        buttonGroup1.add(q9opt1);
        q9opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q9opt1.setText("catch");

        buttonGroup1.add(q9opt2);
        q9opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q9opt2.setText("try");

        buttonGroup1.add(q9opt3);
        q9opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q9opt3.setText("throw");

        buttonGroup1.add(q9opt4);
        q9opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q9opt4.setText("All of the above");
        q9opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9opt4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("What is the return type of the hashCode() method in Java?");

        buttonGroup2.add(q10opt1);
        q10opt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q10opt1.setText("int");

        buttonGroup2.add(q10opt2);
        q10opt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q10opt2.setText("long");

        buttonGroup2.add(q10opt3);
        q10opt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q10opt3.setText("double");

        buttonGroup2.add(q10opt4);
        q10opt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q10opt4.setText("String");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        q9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q9.setText("9");

        q10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        q10.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q10)
                    .addComponent(q9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q9opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q9opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q9opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q9opt4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q10opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q10opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q10opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(q10opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(201, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(q9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q9opt1)
                    .addComponent(q9opt2)
                    .addComponent(q9opt3)
                    .addComponent(q9opt4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(q10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q10opt1)
                    .addComponent(q10opt2)
                    .addComponent(q10opt3)
                    .addComponent(q10opt4))
                .addGap(7, 7, 7)
                .addComponent(t1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q9opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9opt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9opt4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int qid9=Integer.parseInt(q9.getText());
        int qid10=Integer.parseInt(q10.getText());
        
        String res9="";
        String res10="";
                
                if(q9opt1.isSelected()==true)
                { 
                    res9=q9opt1.getText();
                }
                else if(q9opt2.isSelected()==true)
                { 
                    res9=q9opt2.getText(); 
                }
                else if(q9opt3.isSelected()==true)
                { 
                    res9=q9opt3.getText();  
                }
                else if(q9opt4.isSelected()==true)
                { 
                    res9=q9opt4.getText();  
                }
                else if(q9opt1.isSelected()==false&&q9opt2.isSelected()==false&&q9opt3.isSelected()==false&&q9opt4.isSelected()==false)
                {
                    notatp++;
                }
                
                if(q10opt1.isSelected()==true)
                { 
                    res10=q10opt1.getText();
                }
                else if(q10opt2.isSelected()==true)
                { 
                    res10=q10opt2.getText(); 
                }
                else if(q10opt3.isSelected()==true)
                { 
                    res10=q10opt3.getText();  
                }
                else if(q10opt4.isSelected()==true)
                { 
                    res10=q10opt4.getText();  
                }
                else if(q10opt1.isSelected()==false&&q10opt2.isSelected()==false&&q10opt3.isSelected()==false&&q10opt4.isSelected()==false)
                {
                    notatp++;
                }
                else{
                    System.out.println("Wrong...");
                }      
                int count2 = 0;
                int total=0;
                int attempt=0;
                try{
                    Connection con=ConnectionCode.getcon();
                    Statement st=con.createStatement();
                    ResultSet rs=st.executeQuery("Select qus_id,answer_key from questionsjava");
                    while(rs.next()){
                        if (count2 >= 8 && count2 < 10) {
                        int qus_id=rs.getInt("qus_id");
                        String ans1=rs.getString("answer_key");
                        //System.out.println(qus_id);
                        //System.out.println(ans1);
                        
                        if(qid9==qus_id && res9.equals(ans1)){
                            score++;
                        }
                        else if(qid10==qus_id && res10.equals(ans1)){
                            score++;
                        }
                        else{
                            count++;
                        }
                        total=score*5;
                        attempt=10-notatp;
                        System.out.println("score is "+score);
                        System.out.println("count is "+count);
                        System.out.println("attempted qus are "+attempt);
                        System.out.println("total is "+total);
                        }
                        count2++;
                        
                    }  
                }catch(Exception e){
                    System.out.println(" "+e);
                }
                int score3=score;
                int count3=count;
                int total3=total;
                int ntatp=notatp;
                int atp=attempt;
                String us=usname;
                String tp=topic5;
                try{
                    Connection con=ConnectionCode.getcon();
                    Statement st=con.createStatement();
                    st.executeUpdate("insert into result values('"+us+"','"+tp+"','"+score3+"','"+count3+"','"+atp+"','"+ntatp+"','"+total3+"')");
                    System.out.println("Recond Inserted...");
                }catch(Exception e){
                    System.out.println("**********"+e);
                }
                System.out.println("user = "+usname);
                System.out.println("topic = "+topic5);
                
                String atp4=Integer.toString(atp);
                String score4=Integer.toString(score3);
                String count4=Integer.toString(count3);
                String total4=Integer.toString(total3);
                
                this.dispose();
                QuizResult qr=new QuizResult(atp4,score4,count4,total4);
                qr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.toBack();
        new QusJava2().toFront();
        new QusJava2().setState(javax.swing.JFrame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QusJava3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QusJava3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QusJava3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QusJava3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new QusJava3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel q10;
    private javax.swing.JRadioButton q10opt1;
    private javax.swing.JRadioButton q10opt2;
    private javax.swing.JRadioButton q10opt3;
    private javax.swing.JRadioButton q10opt4;
    private javax.swing.JLabel q9;
    private javax.swing.JRadioButton q9opt1;
    private javax.swing.JRadioButton q9opt2;
    private javax.swing.JRadioButton q9opt3;
    private javax.swing.JRadioButton q9opt4;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    // End of variables declaration//GEN-END:variables
}
